### ISSUE TITLE
Bi-directional ManyToOne

### ISSUE THREAD

**Issue by jean-gui** [DamienHarper/DoctrineAuditBundle#139]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.2.1
| PHP version                 | 7.3
| Database                    | MySQL (and lmost likely any database engine)

#### Summary

When you have bi-directionnal ManyToOne associations and if you follow https://symfony.com/doc/current/doctrine/associations.html#setting-information-from-the-inverse-side for setting information from the inverse side, then depending on which setter you use, an "associate" audit is created or not. I think it should be created in both cases without requiring any changes to the entities.

#### How to reproduce

```php
/**
 * @Auditable()
 */
class User
{
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Email", mappedBy="user", orphanRemoval=true)
     */
    private $emails;

    public function addEmail(Email $email): self
    {
        if (!$this->emails->contains($email)) {
            $this->emails[] = $email;
            $email->setUser($this);
        }

        return $this;
    }

    /* ... */
```

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\EmailRepository")
 * @Auditable()
 */
class Email
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="emails")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /* ... */
}
```

```php
        $user = $userRepository->find(1);

        $email = new Email();
        $em->persist($email);

        $email->setUser($user); // does NOT create an "association" audit entry
        $user1->addEmail($email); // creates an "association" audit entry
```

#### Expected behavior

I would have expected `$email->setUser($user)` to create an "association" audit entry in User audit table but only `$user1->addEmail($email)` does.
The other side of the association is properly audited as a property change (although it would be nice to have a link to the related entity).

**Comment by DamienHarper** [comment]
@jean-gui I understand what you expect but the bundle relies on Doctrine and [this is the way Doctrine works internally](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/unitofwork-associations.html#important-concepts):
> Doctrine will only check the owning side of an association for changes.
[...]
Changes made only to the inverse side of an association are ignored. Make sure to update both sides of a bidirectional association (or at least the owning side, from Doctrine's point of view)

Following this last sentence, you have to change your entities to get the behavior you expect.

```php
/**
 * @Auditable()
 */
class User
{
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Email", mappedBy="user", orphanRemoval=true)
     */
    private $emails;

    public function addEmail(Email $email): self
    {
        if (!$this->emails->contains($email)) {
            $this->emails[] = $email;
            $email->setUser($this);
        }

        return $this;
    }

    /* ... */
```

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\EmailRepository")
 * @Auditable()
 */
class Email
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="emails")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function setUser(?User $user): self
    {
        if (null === $user) {
        	$this->user = $user;
        } else {
        	$user->addEmail($this);
        }

        return $this;
    }

    /* ... */
}
```

Note: I didn't test the above code but it should do the trick.

**Comment by jean-gui** [comment]
@DamienHarper Thanks.
Even if Doctrine doesn't monitor the other side of the relationship, I believe it is still possible to get information about the inverse side. 
I don't remember very well how it works as it was a long time ago but I have done something along those lines in https://github.com/w3c/W3CLifecycleEventsBundle#onchange. IIRC the code for handling that is at https://github.com/w3c/W3CLifecycleEventsBundle/blob/master/EventListener/LifecycleEventsListener.php#L306 (and probably other places for other cases).

Would something similar work for this bundle?

**Comment by DamienHarper** [comment]
@jean-gui well I also thought about something like this before (using entity metadata to get such information). 
It should work but would add overhead on every audit operation, mainly because we would have to:
- iterate over every item in entity changeset and check if it belong to the inverse side of a relationship 
- alter or construct the relevant audit entries depending on the changeset itself and the result of the above step

To illustrate the second point above, let's imagine we have an entity being persisted having several fields updated:
- one of them is the inverse side of a relationship and is not null but was null before (association) (case 1)
- one of them is the inverse side of a relationship and is null but was not null before (dissociation) (case 2)
- one of them is the inverse side of a relationship and is not null and was not null before (dissociation + association) (case 3)

=> We'd have to create 5 audit entries:
- one for the update operation
- one to reflect the association event (case 1)
- one to reflect the dissociation event (case 2)
- one to reflect the dissociation event (case 3)
- one to reflect the association event (case 3)

I have this on my todo list as a "maybe one day" item but if you wish to contribute, feel free to submit a PR, it will be appreciated ;)

**Comment by jean-gui** [comment]
Agreed, there is some overhead and multiple cases to take into account. Unfortunately I'm afraid I won't have time to submit a PR. I'll see about changing my entities and if someday the feature gets implemented I'll be very happy!
