### ISSUE TITLE
Override twig view

### ISSUE THREAD

**Issue by KlausK18** [DamienHarper/DoctrineAuditBundle#190]
Hello,

I'm trying to override the layout.html.twig, and as the Symfony doc says, I have created the related path to the new view.
![image](https://user-images.githubusercontent.com/28428653/79733130-ee4ee380-82f4-11ea-9a22-0afb65c8b413.png)
But when I go to the viewer page in /audits it doesn't override it, keeps using the vendor view.
I'm working in dev environment, and I have tried to clean cache many times.

Is this because the bundle doesn't permit it? Bug? Am I doing something wrong?

Thank you!

**Comment by DamienHarper** [comment]
Hi @KlausK18!
You made a typo in the name of the folder in which you can override templates for this bundle. It has to be `DHDoctrineAuditBundle` instead of `DoctrineAuditBundle`.

So the full path of your custom `layout.html.twig` (relative to your project root) should be `templates/bundles/DHDoctrineAuditBundle/layout.html.twig`

**Comment by DamienHarper** [comment]
I close this issue, @KlausK18 feel free to reopen if needed.

**Comment by ganti** [comment]
FYI: with the current version `templates/bundles/DHAuditorBundle/layout.html.twig` works
