### ISSUE TITLE
Symfony 5.3.9 - Attempted to call an undefined method named "fetchColumn" of class "Doctrine\DBAL\Result".

### ISSUE THREAD

**Issue by gsirin** [DamienHarper/DoctrineAuditBundle#279]
I am wondering that audit is not working with Symfony 5.3.9.
When I rollback to 5.3.7 evertyhing works as expected.

Are you aware of this? Do you need further information? If so, how can I help?

**Comment by janklan** [comment]
I ran in the same issue. If `doctrine/dbal` is already at `^3.0.0`, Composer won't upgrade to `damienharper/auditor@1.3.1` because of the version conflict, so the issue remains unresolved. 

So I added `"doctrine/dbal": "<3.0.0",` to my `composer.json` to force it togo down a version, which in turn installed `damienharper/auditor@1.3.1` when I ran `composer update`. Happy days.

I then assumed it was safe to remove the `doctrine/dbal` version constraint because the correct `damienharper/auditor` version was already installed, but doing so and running `composer update` reverted the whole lot by downgrading `damienharper/auditor` and upgrading `doctrine/dbal` instead. 

Unless I'm doing it wrong, I'm about to be stuck with outdated dependencies when the new major `damienharper/auditor` supporting the newer `doctrine/dbal` 

@DamienHarper would you mind, please, leaving a message in this thread, when the new version is out? I'm not quite sure where else can I sign up to get notified, other than watching this issue?

**Comment by DamienHarper** [comment]
@janklan New releases are out!
damienharper/auditor 2.0
damienharper/auditor-bundle 5.0

**Comment by janklan** [comment]
You're a legend, mate.
