### ISSUE TITLE
separate DB for audit logs

### ISSUE THREAD

**Issue by nnmer** [DamienHarper/DoctrineAuditBundle#41]
Hi,

Can we have audit logs to be stored in a separate DB through another DB connection and entityManager? From the first look seems that is not possible by simple reassign other entityManager to related services. But not sure how much work would be needed to add such functionality.

UPD:
Just want to share the idea behind.
When the entities are used actively, the _audit tables are growing rather fast. Also this data is not the most important to have.
The one solution would be to implement some rotation policy and move old data to another db. But better would be to store this audit data directly to a "secondary" database

**Comment by DamienHarper** [comment]
@nnmer I'm thinking about using a secondary db since the beginning but my main concern with this is that all operations won't be processed in a single transaction. Right now, the bundle wraps audit operations (inserts into _audit tables) in the same transaction than the audited entities operations so that every thing is "atomic". This can't be the same using two databases because a transaction can't span over two separate connections/databases.

Regarding audit tables that keep growing, the bundle features a [cleaning command](https://github.com/DamienHarper/DoctrineAuditBundle#audits-cleanup)

**Comment by nnmer** [comment]
@DamienHarper Agree, the 'atomicity' still takes precedence

**Comment by DamienHarper** [comment]
PR #76 has been merged allowing such feature.
